function pre_install(desc)
    mkdir('inst')
    movefile({'xerces'...
              'isOctave.m'...
              'jsonread.m'...
              'jsonwrite.m'...
              'readxml.m'...
              'writexml.m'...
              },'inst');
end
